### PR TITLE
Increase the texture size to 2048×2048 for all examples

### PR DESCRIPTION
**Pull request by Calinou**
This makes example textures look better.

This also fixes the example texture sizes being too low after #38.

**Don't merge yet – see the comment below.**

### CODE REVIEW

**Comment by Calinou** [comment]
I realized we may want to store the `size` attribute as an absolute power of two value, rather than an OptionButton index. This way, it won't break if we change the OptionButton's minimum value.

I can open a PR for this, and amend this one if you like the idea :slightly_smiling_face:

**Comment by RodZill4** [comment]
> I realized we may want to store the `size` attribute as an absolute power of two value, rather than an OptionButton index.

Yes, this is how it should be, I guess.

**Comment by RodZill4** [comment]
I just pushed the size parameter changes (does not depend on the minimum value of the parameter anymore) and resized all examples to 2048x2048.

**Comment by Calinou** [comment]
Thanks!

I guess this PR can be closed then :slightly_smiling_face:

**Pull request closed without merging**
